name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test containers
        run: docker compose up --build -d
      - name: Tear down
        if: always()
        run: docker compose down
